#!/usr/bin/env python3
import sys
import computor as __computor__

if __name__ == "__main__" :
	global verbose
	verbose = False
	if len(sys.argv) == 2 or (len(sys.argv) == 3 and (sys.argv[1] == "-v" or sys.argv[1] == "--verbose")) :
		entry = sys.argv[len(sys.argv) - 1]
		if len(sys.argv) == 3 :
			verbose = True
	else :
		print("Usage : ./computor [flags] equation")
		print()
		print("	flags : 	-v, --verbose : Print calculation's steps")
		print()
		print("	equation : 	Type an equation with the format a * X^n")
		print("				Example : 5 * X^0 + 4 * X^1 - 9.3 * X^2 = 1 * X^0 + -2.1Y^4.2 + 2,1 *  Y^4.2 - -3X + 2 + X * -3")
		print()
		entry = input("Equation : ")
		if not entry :
			__computor__.error("No input equation")
	equation = __computor__.equation(entry, verbose)
